Adding code to capture additional output from github actions

diff --git a/.github/workflows/get_listings.yml b/.github/workflows/get_listings.yml
--- a/.github/workflows/get_listings.yml
+++ b/.github/workflows/get_listings.yml
@@ -25,7 +25,10 @@ jobs:
           CLIENT_ID: ${{ secrets.CLIENT_ID }}
           CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
         run: |
-          python -m scripts.get_sold_listings || echo "get_sold_listings failed with error: $?"
+          python -m scripts.get_sold_listings > get_sale_listings.log 2>&1
+          if [[ $? -ne 0 ]]; then
+            echo "get_sale_listings failed. Check get_sale_listings.log for details."
+          fi
         continue-on-error: true
 
       - name: Run get_sale_listings
@@ -33,7 +36,10 @@ jobs:
           CLIENT_ID: ${{ secrets.CLIENT_ID }}
           CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
         run: |
-          python -m scripts.get_sale_listings || echo "get_sale_listings failed with error: $?"
+          python -m scripts.get_sale_listings > get_sale_listings.log 2>&1
+          if [[ $? -ne 0 ]]; then
+            echo "get_sale_listings failed. Check get_sale_listings.log for details."
+          fi
         continue-on-error: true
 
       - name: Commit and push changes
